name: Release and Publish
on:
  push:
    # 监听 main 分支
    branches:
      - main
# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
jobs:
  # 设置 release-please 任务
  release-please:
    # 设置任务运行环境为 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      # 使用 release-please-action 动作来自动创建发布 PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # 设置发布类型为 node
          release-type: node
          # 秘钥
          token: ${{ secrets.ACCESS_TOKEN }}
